In [2]:

import numpy as np

def softmax(x):
    # 计算每行的最大值
    row_max = np.max(x)
    print(row_max)
    # 每行元素都需要减去对应的最大值，否则求exp(x)会溢出，导致inf情况
    x = x - row_max
    # 计算e的指数次幂
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp)
    s = x_exp / x_sum
    return s

a = [11,9,10]
A = np.array(a)
print(A)
softmax(A)

[11  9 10]
11


array([0.66524096, 0.09003057, 0.24472847])

In [2]:

# -*-coding: utf-8 -*-
import numpy as np
 
def softmax(x, axis=1):
    # 计算每行的最大值
    row_max = x.max(axis=axis)
 
    # 每行元素都需要减去对应的最大值，否则求exp(x)会溢出，导致inf情况
    # reshape函数用于更改数据的列数和行数，(-1, 1)变为一列，(1, -1)变为一行
    row_max=row_max.reshape(-1, 1)
    x = x - row_max
 
    # 计算e的指数次幂
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis=axis, keepdims=True)
    s = x_exp / x_sum
    return s
 
 
A = [[1, 1, 5, 3],
     [0.2, 0.2, 0.5, 0.1]]
A= np.array(A)
axis = 1  # 默认计算最后一维
 
# 使用自定义softmax
s1 = softmax(A, axis=axis)
print("s1:{}".format(s1))

s1:[[0.01562812 0.01562812 0.85326667 0.11547709]
 [0.23503441 0.23503441 0.31726326 0.21266793]]
